#기존엔 여기 있는거 안 썼는데 secret file을 따로 관리하기 때문에 이거 그대로 써도 됨
services:
  server:
    image: post-here:test
    container_name: postHere
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ~/postHere/log/testTT-log:/var/log/testTT-log
      - ~/postHere/config/:/var/config/ #application-secret.yml 파일 및 각종 설정 파일 바인딩 마운트
    networks:
      - postHereNet
    ports:
      - 8081:8081
    restart: no

networks:
  postHereNet: