#기존엔 여기 있는거 안 썼는데 secret file을 따로 관리하기 때문에 이거 그대로 써도 됨
#근데 jenkins에서 build해서 이미지 만들고 host server에선 만들어진 이미지 불러와서 컨테이너 실행할 것이기 때문에 여깄는 docker compose 파일은 실제로는 쓰이지 않음
#host server에 docker compose 파일만 따로 두고 그 파일을 이용하는 방식으로 활용
services:
  server:
    image: post-here:latest
    container_name: postHere
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ~/postHere/log/postHere-log:/var/log/postHere-log
      - ~/postHere/config/:/var/config/ #application-secret.yml 파일 및 각종 설정 파일 바인딩 마운트
    networks:
      - postHereNet
    ports:
      - 8081:8081
    restart: no

networks:
  postHereNet: