spring:
  profiles:
    default: default
  config:
    import: optional:application-secret.yml
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:/var/config/application-secret.yml

logging:
  level:
    # 트랜잭션 흐름 디버깅
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG
    # SQL/파라미터 로그
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    # 프로젝트 패키지 전체 디버깅
    io.github.nokasegu.post_here: DEBUG

  file:
    path: /var/log/postHere-log

---
spring:
  config:
    import: "optional:classpath:application-secret.yml"
